### ISSUE TITLE
组件粘贴时报错？

### ISSUE THREAD

**Issue by staymo** [SeriaWei/ZKEACMS.Core#126]
![image](https://user-images.githubusercontent.com/20747803/34520676-a6727cbc-f0c4-11e7-954a-2b6148f917da.png)

**Comment by SeriaWei** [comment]
这个问题在develop分支已经改了
https://github.com/SeriaWei/ZKEACMS.Core/blob/develop/src/ZKEACMS/Common/Service/NavigationWidgetService.cs#L40

**Comment by staymo** [comment]
OK
