### ISSUE TITLE
演示地址后台登不上了好像

### ISSUE THREAD

**Issue by gebiWangshushu** [SeriaWei/ZKEACMS.Core#209]
演示地址后台登不上了好像？

**Comment by SeriaWei** [comment]
用户名和密码都是admin。
我刚试了可以，你可以看一下登录界面的右下解是不是有这个图标，如果没有是不能登录的。
![image](https://user-images.githubusercontent.com/6006218/44008170-dd078f76-9ed2-11e8-8ad0-0c7660a7f987.png)

**Comment by gebiWangshushu** [comment]
感谢回复，今天换台电脑，可以了~

**Comment by gebiWangshushu** [comment]
还有，加油！东西很好~

**Comment by SeriaWei** [comment]
谢谢
