### ISSUE TITLE
在文章詳情頁面，快速設計頁面工具欄 點擊編輯，鏈接錯誤

### ISSUE THREAD

**Issue by w805756054** [SeriaWei/ZKEACMS.Core#222]
![2](https://user-images.githubusercontent.com/14989628/45011045-1c5db200-b043-11e8-9374-23779d56203e.png)
![1](https://user-images.githubusercontent.com/14989628/45011046-1c5db200-b043-11e8-8dad-f06a8a0b6c7c.png)

**Comment by SeriaWei** [comment]
这个问题之前已经fix了，#6e6ac0882cf4ee92c6dee0a047ac36d6227ac641
