### ISSUE TITLE
请问怎么跑单元测试？

### ISSUE THREAD

**Issue by wyongwei** [SeriaWei/ZKEACMS.Core#259]
比如，我想测试IArticleService .Publish方法

**Comment by SeriaWei** [comment]
目前我们没有写对Service的单元测试代码。您可以按微软官方文档添加单元测试代码
https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test

**Comment by wyongwei** [comment]
好的，谢谢！我其实更想问的是单元测试怎么跑起来，而不是怎么建单元测试。稍后我仔细看下您分享的链接。
另外，我琢磨着跑了一个单元测试，如下，可以跑通基本的方法。


`using Easy;
using Easy.Constant;
using Easy.Modules.MutiLanguage;
using Easy.RepositoryPattern;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Text;
using ZKEACMS.Article.Models;
using ZKEACMS.Article.Service;
using ZKEACMS.DbConnectionPool;
using ZKEACMS.Options;
using ZKEACMS.WebHost;

namespace ZKEACMS.Article.Tests
{
    [TestClass]
    public class ArticleServiceTests
    {
        public ServiceProvider ServiceProvider { get; set; }
        public ArticleServiceTests()
        {
            ServiceCollection services = new ServiceCollection();

            services.AddSingleton(new DbConnectionPool.Options() { MaximumRetained = 128 });
            services.AddSingleton(new DatabaseOption
            {
                DbType = DbTypes.MySql,
                ConnectionString = "Server=localhost;Database=ZKEACMS_Core;User Id=root;Password=chen7074;"
            });

            services.AddSingleton<Easy.RepositoryPattern.IOnModelCreating, Easy.EntityFrameWorkModelCreating>();//         
            services.AddSingleton<Easy.RepositoryPattern.IOnModelCreating, ZKEACMS.Article.EntityFrameWorkModelCreating>();//      

            services.AddSingleton<IDatabaseConfiguring, EntityFrameWorkConfigure>();//单例的
            services.AddTransient<IArticleService, ArticleService>();

            services.TryAddScoped<IApplicationContext, CMSApplicationContext>();
            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<IHostingEnvironment, MyHostingEnvironment>();
            services.AddTransient<ILocalize, Localize>();



            services.AddSingleton<IDbConnectionPool, SimpleDbConnectionPool>();
            services.AddScoped<IConnectionHolder, TransientConnectionHolder>();
            services.AddDbContextOptions<CMSDbContext>();
            services.AddDbContext<CMSDbContext>();
            //
            ServiceProvider = services.BuildServiceProvider();
        }
        [TestMethod]
        public void PublishTest()
        {
            //获取实例对象
            IArticleService service = ServiceProvider.GetService<IArticleService>();

            ////调用方法
            service.Publish(1);

            //验证效果
        }
        [TestMethod]
        public void CreateTest()
        {
            //获取实例对象
            IArticleService service = ServiceProvider.GetService<IArticleService>();

            ArticleEntity entity = new ArticleEntity
            {
                ActionType = ActionType.Create,
                ArticleContent = "ArticleContent",
                ArticleTypeID = 2,
                Counter = 0,
                CreateBy = "admin",
                CreatebyName = "ZKEASOFT",
                CreateDate = DateTime.Now,
                Description = "Description",
                ID = 4,
                ImageThumbUrl = "/images/09.jpg",
                ImageUrl = null,
                IsPublish = false,
                LastUpdateBy = "admin",
                LastUpdateByName = "ZKEASOFT",
                LastUpdateDate = DateTime.Now,
                MetaDescription = "MetaDescription",
                MetaKeyWords = "MetaKeyWords",
                PublishDate = null,
                Status =1,
                Summary = "Summary",
                Title = "Title",
                Url = "article2"
            };
            ServiceResult<ArticleEntity> addResult = service.Add(entity);

            //验证效果
        }
    }
}
`

**Comment by wyongwei** [comment]
其中遇到的几个问题如下：
1：依赖注入的类型问题
2：各插件中的EntityFrameWorkModelCreating类型注入问题
3：IArticleService.Update()方法中，ServiceBase<T>.Validate()--->ServiceLocator.GetViewConfigure(typeof(T))    方法需要依赖HttpContext的问题


目前我只测试了这几个基础的方法，分别遇到了以上问题，都通过变通、临时方案解决了。能让单元测试跑通。
