### ISSUE TITLE
docker 运行起来以后 ，登录进入后天跳转失败

### ISSUE THREAD

**Issue by luguizhou** [SeriaWei/ZKEACMS.Core#260]
**Describe the bug**
docker 运行起来以后 登录进入口泰

我用admin admin 登录以后访问失败

该网页无法正常运作
如果问题仍然存在，请与网站所有者联系。
HTTP ERROR 400

**Comment by SeriaWei** [comment]
我在我的环境下没有重现你这个问题
```
docker run -d -p 80:80 zkeasoft/zkeacms
```
你可以使用这个地址访问，这是临时的，我很快就清掉

http://52.163.231.199/index

能否提供更详细的一些信息？

**Comment by SeriaWei** [comment]
我的环境是 Ubuntu 16.04, Docker version 18.09.0

**Comment by luguizhou** [comment]
我再更新了一下镜像就可以了
