### ISSUE TITLE
导航添加二级菜单后父级菜单无法完成跳转

### ISSUE THREAD

**Issue by sulexiu** [SeriaWei/ZKEACMS.Core#261]

**Comment by SeriaWei** [comment]
**这遵循的是移动设备优先的设计原则**

因为父级菜单的功能已经变成了点击打开子菜单，你可以在子菜单多个一个父级的链接。

如果要响应点击跳转，可以改成鼠标经过时展开二级菜单，但这会导致手机下不方便展开子菜单。
