### ISSUE TITLE
没有找到mysql数据库创建语句

### ISSUE THREAD

**Issue by aysun168** [SeriaWei/ZKEACMS.Core#72]

**Comment by SeriaWei** [comment]
没有提供MySql数据库脚本，可以自己用工具转，或者在群共享里面下载。有热心的网友有生成。
## QQ群(493586356)
![QQ群493586356](http://ww3.sinaimg.cn/mw690/005zTNGqgw1f7l3g7ybdfj307609uq3m.jpg)
