### ISSUE TITLE
没有必要用表达式树，直接用委托即可

### ISSUE THREAD

**Issue by tangdf** [SeriaWei/ZKEACMS.Core#84]
[https://github.com/SeriaWei/ZKEACMS.Core/blob/search/src/EasyFrameWork/ViewPort/jsTree/Tree.cs#L133](https://github.com/SeriaWei/ZKEACMS.Core/blob/search/src/EasyFrameWork/ViewPort/jsTree/Tree.cs#L133)
参数是表达式树，马上又编译成为委托，而且这个编译的过程是很耗性能的；
直接用委托不就可以了吗？

**Comment by SeriaWei** [comment]
感谢反馈，可以直接使用委托。
